### ISSUE TITLE
Проблема такая, с однрой стороны ээто очень мало, с другой если увеличить, а числа будут маленькие то будет избыточно. Хорошо бы использовать ровно столько сколько нужно

### ISSUE THREAD

**Issue by ahvastunov-itmo** [kav128/bna#11]
https://github.com/kav128/bna/blob/96692d9ba8ecdf0ec74ea434c2387228ff6b1f61/BignumArithmetic/Operations.c#L10

**Comment by kav128** [comment]
Это значение по умолчанию. Мы его можем изменить, запустив программу с параметром `-bsize n`, где `n` - необходимое значение.
