### ISSUE TITLE
Идея понятна, но из-за этого приходится пробегаться по каждому числу лишний раз, эфффективнее будет проделывать это в операциях

### ISSUE THREAD

**Issue by ahvastunov-itmo** [kav128/bna#7]
https://github.com/kav128/bna/blob/96692d9ba8ecdf0ec74ea434c2387228ff6b1f61/BignumArithmetic/Source.c#L29

**Comment by kav128** [comment]
В этой строке идет проверка числа, переданного в аргументах командной строки, а не операнда для вычисления, и выполняется она только один раз
