### ISSUE TITLE
Операция очень дорогая по памяти получилась. Не очень ясно зачем дополнительная память в этом месте

### ISSUE THREAD

**Issue by ahvastunov-itmo** [kav128/bna#9]
https://github.com/kav128/bna/blob/96692d9ba8ecdf0ec74ea434c2387228ff6b1f61/BignumArithmetic/Utils.c#L106

**Comment by kav128** [comment]
В этой функции дальше по коду отбрасывается знак у числа и отбрасываются лидирующие нули. Чтобы не портить внешнюю строку, эти операции выполняются в отдельной памяти, которая потом освобождается.
